[package]
name = "cookie_clicker"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14", features = ["default"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"